=== api-evangelist/amazon-direct-connect/json-schema/amazon-direct-connect-new-private-virtual-interface-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-direct-connect/refs/heads/main/json-schema/amazon-direct-connect-new-private-virtual-interface-schema.json",
  "title": "NewPrivateVirtualInterface",
  "description": "Information about a private virtual interface.",
  "type": "object",
  "properties": {
    "virtualInterfaceName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VirtualInterfaceName"
        },
        {
          "description": "The name of the virtual interface assigned by the customer network. The name has a maximum of 100 characters. The following are valid characters: a-z, 0-9 and a hyphen (-)."
        }
      ]
    },
    "vlan": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VLAN"
        },
        {
          "description": "The ID of the VLAN."
        }
      ]
    },
    "asn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ASN"
        },
        {
          "description": "<p>The autonomous system (AS) number for Border Gateway Protocol (BGP) configuration.</p> <p>The valid values are 1-2147483647.</p>"
        }
      ]
    },
    "mtu": {
      "allOf": [
        {
          "$ref": "#/components/schemas/MTU"
        },
        {
          "description": "The maximum transmission unit (MTU), in bytes. The supported values are 1500 and 9001. The default value is 1500."
        }
      ]
    },
    "authKey": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BGPAuthKey"
        },
        {
          "description": "The authentication key for BGP configuration. This string has a minimum length of 6 characters and and a maximun lenth of 80 characters."
        }
      ]
    },
    "amazonAddress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AmazonAddress"
        },
        {
          "description": "The IP address assigned to the Amazon interface."
        }
      ]
    },
    "customerAddress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CustomerAddress"
        },
        {
          "description": "The IP address assigned to the customer interface."
        }
      ]
    },
    "addressFamily": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AddressFamily"
        },
        {
          "description": "The address family for the BGP peer."
        }
      ]
    },
    "virtualGatewayId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VirtualGatewayId"
        },
        {
          "description": "The ID of the virtual private gateway."
        }
      ]
    },
    "directConnectGatewayId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DirectConnectGatewayId"
        },
        {
          "description": "The ID of the Direct Connect gateway."
        }
      ]
    },
    "tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagList"
        },
        {
          "description": "The tags associated with the private virtual interface."
        }
      ]
    },
    "enableSiteLink": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EnableSiteLink"
        },
        {
          "description": "Indicates whether to enable or disable SiteLink."
        }
      ]
    }
  },
  "required": [
    "virtualInterfaceName",
    "vlan",
    "asn"
  ]
}

=== api-evangelist/amazon-direct-connect/examples/amazon-direct-connect-new-private-virtual-interface-example.json
{
  "virtualInterfaceName": "Example virtualInterfaceName",
  "vlan": "123",
  "asn": "example-asn",
  "mtu": "example-mtu",
  "authKey": "example-authKey",
  "amazonAddress": "example-amazonAddress",
  "customerAddress": "example-customerAddress",
  "addressFamily": "example-addressFamily",
  "virtualGatewayId": "dxcon-abc123456",
  "directConnectGatewayId": "dxcon-abc123456",
  "tags": "example-tags",
  "enableSiteLink": "example-enableSiteLink"
}
