=== api-evangelist/amazon-direct-connect/json-schema/amazon-direct-connect-bgp-peer-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-direct-connect/refs/heads/main/json-schema/amazon-direct-connect-bgp-peer-schema.json",
  "title": "BGPPeer",
  "description": "Information about a BGP peer.",
  "type": "object",
  "properties": {
    "bgpPeerId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BGPPeerId"
        },
        {
          "description": "The ID of the BGP peer."
        }
      ]
    },
    "asn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ASN"
        },
        {
          "description": "The autonomous system (AS) number for Border Gateway Protocol (BGP) configuration."
        }
      ]
    },
    "authKey": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BGPAuthKey"
        },
        {
          "description": "The authentication key for BGP configuration. This string has a minimum length of 6 characters and and a maximun lenth of 80 characters."
        }
      ]
    },
    "addressFamily": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AddressFamily"
        },
        {
          "description": "The address family for the BGP peer."
        }
      ]
    },
    "amazonAddress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AmazonAddress"
        },
        {
          "description": "The IP address assigned to the Amazon interface."
        }
      ]
    },
    "customerAddress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CustomerAddress"
        },
        {
          "description": "The IP address assigned to the customer interface."
        }
      ]
    },
    "bgpPeerState": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BGPPeerState"
        },
        {
          "description": "<p>The state of the BGP peer. The following are the possible values:</p> <ul> <li> <p> <code>verifying</code>: The BGP peering addresses or ASN require validation before the BGP peer can be created. This state applies only to public virtual interfaces.</p> </li> <li> <p> <code>pending</code>: The BGP peer is created, and remains in this state until it is ready to be established.</p> </li> <li> <p> <code>available</code>: The BGP peer is ready to be established.</p> </li> <li> <p> <code>deleting</code>: The BGP peer is being deleted.</p> </li> <li> <p> <code>deleted</code>: The BGP peer is deleted and cannot be established.</p> </li> </ul>"
        }
      ]
    },
    "bgpStatus": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BGPStatus"
        },
        {
          "description": "<p>The status of the BGP peer. The following are the possible values:</p> <ul> <li> <p> <code>up</code>: The BGP peer is established. This state does not indicate the state of the routing function. Ensure that you are receiving routes over the BGP session.</p> </li> <li> <p> <code>down</code>: The BGP peer is down.</p> </li> <li> <p> <code>unknown</code>: The BGP peer status is not available.</p> </li> </ul>"
        }
      ]
    },
    "awsDeviceV2": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AwsDeviceV2"
        },
        {
          "description": "The Direct Connect endpoint that terminates the BGP peer."
        }
      ]
    },
    "awsLogicalDeviceId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AwsLogicalDeviceId"
        },
        {
          "description": "The Direct Connect endpoint that terminates the logical connection. This device might be different than the device that terminates the physical connection."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-direct-connect/examples/amazon-direct-connect-bgp-peer-example.json
{
  "bgpPeerId": "dxcon-abc123456",
  "asn": "example-asn",
  "authKey": "example-authKey",
  "addressFamily": "example-addressFamily",
  "amazonAddress": "example-amazonAddress",
  "customerAddress": "example-customerAddress",
  "bgpPeerState": "available",
  "bgpStatus": "available",
  "awsDeviceV2": "example-awsDeviceV2",
  "awsLogicalDeviceId": "dxcon-abc123456"
}
