=== api-evangelist/amazon-direct-connect/json-schema/amazon-direct-connect-interconnect-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-direct-connect/refs/heads/main/json-schema/amazon-direct-connect-interconnect-schema.json",
  "title": "Interconnect",
  "description": "Information about an interconnect.",
  "type": "object",
  "properties": {
    "interconnectId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/InterconnectId"
        },
        {
          "description": "The ID of the interconnect."
        }
      ]
    },
    "interconnectName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/InterconnectName"
        },
        {
          "description": "The name of the interconnect."
        }
      ]
    },
    "interconnectState": {
      "allOf": [
        {
          "$ref": "#/components/schemas/InterconnectState"
        },
        {
          "description": "<p>The state of the interconnect. The following are the possible values:</p> <ul> <li> <p> <code>requested</code>: The initial state of an interconnect. The interconnect stays in the requested state until the Letter of Authorization (LOA) is sent to the customer.</p> </li> <li> <p> <code>pending</code>: The interconnect is approved, and is being initialized.</p> </li> <li> <p> <code>available</code>: The network link is up, and the interconnect is ready for use.</p> </li> <li> <p> <code>down</code>: The network link is down.</p> </li> <li> <p> <code>deleting</code>: The interconnect is being deleted.</p> </li> <li> <p> <code>deleted</code>: The interconnect is deleted.</p> </li> <li> <p> <code>unknown</code>: The state of the interconnect is not available.</p> </li> </ul>"
        }
      ]
    },
    "region": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Region"
        },
        {
          "description": "The Amazon Web Services Region where the connection is located."
        }
      ]
    },
    "location": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LocationCode"
        },
        {
          "description": "The location of the connection."
        }
      ]
    },
    "bandwidth": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Bandwidth"
        },
        {
          "description": "The bandwidth of the connection."
        }
      ]
    },
    "loaIssueTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LoaIssueTime"
        },
        {
          "description": "The time of the most recent call to <a>DescribeLoa</a> for this connection."
        }
      ]
    },
    "lagId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LagId"
        },
        {
          "description": "The ID of the LAG."
        }
      ]
    },
    "awsDevice": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AwsDevice"
        },
        {
          "description": "The Direct Connect endpoint on which the physical connection terminates."
        }
      ]
    },
    "jumboFrameCapable": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JumboFrameCapable"
        },
        {
          "description": "Indicates whether jumbo frames (9001 MTU) are supported."
        }
      ]
    },
    "awsDeviceV2": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AwsDeviceV2"
        },
        {
          "description": "The Direct Connect endpoint that terminates the physical connection."
        }
      ]
    },
    "awsLogicalDeviceId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AwsLogicalDeviceId"
        },
        {
          "description": "The Direct Connect endpoint that terminates the logical connection. This device might be different than the device that terminates the physical connection."
        }
      ]
    },
    "hasLogicalRedundancy": {
      "allOf": [
        {
          "$ref": "#/components/schemas/HasLogicalRedundancy"
        },
        {
          "description": "Indicates whether the interconnect supports a secondary BGP in the same address family (IPv4/IPv6)."
        }
      ]
    },
    "tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagList"
        },
        {
          "description": "The tags associated with the interconnect."
        }
      ]
    },
    "providerName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProviderName"
        },
        {
          "description": "The name of the service provider associated with the interconnect."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-direct-connect/examples/amazon-direct-connect-interconnect-example.json
{
  "interconnectId": "dxcon-abc123456",
  "interconnectName": "Example interconnectName",
  "interconnectState": "available",
  "region": "example-region",
  "location": "example-location",
  "bandwidth": "dxcon-abc123456",
  "loaIssueTime": "example-loaIssueTime",
  "lagId": "dxcon-abc123456",
  "awsDevice": "example-awsDevice",
  "jumboFrameCapable": "example-jumboFrameCapab",
  "awsDeviceV2": "example-awsDeviceV2",
  "awsLogicalDeviceId": "dxcon-abc123456",
  "hasLogicalRedundancy": "example-hasLogicalRedun",
  "tags": "example-tags",
  "providerName": "dxcon-abc123456"
}
