=== api-evangelist/amazon-direct-connect/json-schema/amazon-direct-connect-new-public-virtual-interface-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-direct-connect/refs/heads/main/json-schema/amazon-direct-connect-new-public-virtual-interface-schema.json",
  "title": "NewPublicVirtualInterface",
  "description": "Information about a public virtual interface.",
  "type": "object",
  "properties": {
    "virtualInterfaceName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VirtualInterfaceName"
        },
        {
          "description": "The name of the virtual interface assigned by the customer network. The name has a maximum of 100 characters. The following are valid characters: a-z, 0-9 and a hyphen (-)."
        }
      ]
    },
    "vlan": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VLAN"
        },
        {
          "description": "The ID of the VLAN."
        }
      ]
    },
    "asn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ASN"
        },
        {
          "description": "<p>The autonomous system (AS) number for Border Gateway Protocol (BGP) configuration.</p> <p>The valid values are 1-2147483647.</p>"
        }
      ]
    },
    "authKey": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BGPAuthKey"
        },
        {
          "description": "The authentication key for BGP configuration. This string has a minimum length of 6 characters and and a maximun lenth of 80 characters."
        }
      ]
    },
    "amazonAddress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AmazonAddress"
        },
        {
          "description": "The IP address assigned to the Amazon interface."
        }
      ]
    },
    "customerAddress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CustomerAddress"
        },
        {
          "description": "The IP address assigned to the customer interface."
        }
      ]
    },
    "addressFamily": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AddressFamily"
        },
        {
          "description": "The address family for the BGP peer."
        }
      ]
    },
    "routeFilterPrefixes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RouteFilterPrefixList"
        },
        {
          "description": "The routes to be advertised to the Amazon Web Services network in this Region. Applies to public virtual interfaces."
        }
      ]
    },
    "tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagList"
        },
        {
          "description": "The tags associated with the public virtual interface."
        }
      ]
    }
  },
  "required": [
    "virtualInterfaceName",
    "vlan",
    "asn"
  ]
}

=== api-evangelist/amazon-direct-connect/examples/amazon-direct-connect-new-public-virtual-interface-example.json
{
  "virtualInterfaceName": "Example virtualInterfaceName",
  "vlan": "123",
  "asn": "example-asn",
  "authKey": "example-authKey",
  "amazonAddress": "example-amazonAddress",
  "customerAddress": "example-customerAddress",
  "addressFamily": "example-addressFamily",
  "routeFilterPrefixes": "example-routeFilterPref",
  "tags": "example-tags"
}
